Repository intel/gardener-extension-cri-resmgr, pull requests merged in 2022-10, with the labels that each got.

#52 Add documentation for troubleshooting by logs
  README.md
  doc/cri-resmeg-agent-full.png
  doc/cri-resmeg-agent-logs.png
  doc/cri-resmeg-extension.png
  doc/cri-resmeg-installation-full.png
  doc/cri-resmeg-installation-logs.png
  doc/cri-resmeg.png
  doc/fix_grafana_loki.png
Labels: documentation

#61 Fix uninstallation script and fix broken recovery check + only install to containerd nodes
  .gitignore
  .vscode/settings.json
  Dockerfile
  charts/internal/cri-resmgr-installation/templates/agent-deployment.yaml
  charts/internal/cri-resmgr-installation/templates/installaton-configmap.yaml
  charts/internal/cri-resmgr-installation/templates/installaton-daemonset.yaml
  examples/ctrldeploy-ctrlreg.yaml
  examples/shoot.yaml
  examples/shoot2.yaml
  hacks/delete-shoot.sh
  hacks/disable-extension-in-shoot.sh
  hacks/enable-extension-in-shoot.sh
  hacks/export-kubeconfig-for-shoot.sh
  hacks/generate-controller-registration.sh
  hacks/reconcile-extension-trigger.sh
  hacks/reconcile-shoot-trigger.sh
  pkg/consts/COMMIT
  pkg/controller/lifecycle/add.go
Labels: bug

#69 Fix propagate config when clustre unhealthy + generate version/commit based on latest tag/build
  Dockerfile
  Makefile
  README.md
  charts/internal/cri-resmgr-installation/templates/installaton-configmap.yaml
  charts/internal/cri-resmgr-installation/templates/installaton-daemonset.yaml
  examples/ctrldeploy-ctrlreg.yaml
  examples/shoot2.yaml
  hacks/generate-controller-registration.sh
  pkg/consts/COMMIT
  pkg/consts/VERSION
  pkg/consts/consts.go
  pkg/controller/lifecycle/add.go
Labels: bug

#70 Cpu resources for installation and less for agent (one full cpu is not needed)
  charts/internal/cri-resmgr-installation/templates/agent-deployment.yaml
  charts/internal/cri-resmgr-installation/templates/installaton-daemonset.yaml
Labels: enhancement

#71 Handle more deadlocks and races + allow empty config values.
  charts/internal/cri-resmgr-installation/templates/installaton-configmap.yaml
  charts/internal/cri-resmgr-installation/templates/installaton-daemonset.yaml
  examples/ctrldeploy-ctrlreg.yaml
  examples/demo/nginx-sts.yml
  examples/demo/stress-sts.yml
  examples/shoot.yaml
  examples/shoot2.yaml
  hacks/export-kubeconfig-for-shoot.sh
  hacks/generate-controller-registration.sh
  pkg/configs/configs.go
  pkg/controller/lifecycle/add.go
Labels: bug, enhancement
